[package]
name = "cross"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.1"
colored = "2.0.0"
indicatif = "0.16.2"
clipboard = "0.5.0"